### PR TITLE
Fix TypeError during Setup

### LINKED ISSUE #29: TypeError during setup.py install
Calling `python setup.py install` with python 3 leads to the following error:

```Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    (systemd_unit_path(), ['bley.service'])
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python3.6/distutils/command/install.py", line 557, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/install_data.py", line 60, in run
    dir = change_root(self.root, dir)
  File "/usr/lib/python3.6/distutils/util.py", line 149, in change_root
    return os.path.join(new_root, pathname[1:])
  File "/usr/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

### PR DESCRIPTION
**Pull request by todi**
fixes #29

### CODE REVIEW

**Comment by evgeni** [comment]
doesn't this assume the environment of the user is utf-8? which is not always the case?

**Comment by todi** [comment]
You are right of course. Using subprocess.getoutput should get the string with the right encoding automatically.

But honestly, I'm not sure that whole pkg-config call is necessary at all. Are there distributions that do not use the standard /usr/lib/systemd/system directory for their systemd unit files?

**Comment by todi** [comment]
And as Travis reminds me, subprocess.getoutput does not exist in python 2.7 ...
Maybe a different solution then.

**Comment by evgeni** [comment]
While I agree, there are probably no distros using a different path, I'd like to keep the flexibility.

How about
```python
try:
    path = subprocess.getoutput(command)
except AttributeError:
    path = subprocess.check_output(command, stderr=subprocess.STDOUT)
```

**Comment by todi** [comment]
Sounds good

**Comment by evgeni** [comment]
thanks, merged in 9bf6f8a7c835092c9e5d24804d56d38799fc4ab5

**Pull request closed without merging**
